export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR"
export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS"
export const ADD_SHIPPING_ERROR = "ADD_SHIPPING_ERROR"
export const ADD_TO_WHISH_LIST_SUCCESS = 'ADD_TO_WHISH_LIST_SUCCESS'
export const DELETE_WHISH_LIST_ITEM = 'DELETE_WHISH_LIST_ITEM'
export const ADD_TO_WHISH_LIST_ERROR = "ADD_TO_WHISH_LIST_ERROR"

